# Generated by Django 4.2.10 on 2024-02-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=10000, unique=True)),
                ('fam', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=10000)),
                ('otc', models.CharField(max_length=10000)),
                ('phone', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=10000)),
                ('title', models.CharField(max_length=10000)),
                ('other_titles', models.CharField(max_length=10000)),
                ('connect', models.CharField(max_length=10000)),
                ('add_time', models.DateTimeField()),
                ('level_winter', models.CharField(max_length=10000)),
                ('level_summer', models.CharField(max_length=10000)),
                ('level_autumn', models.CharField(max_length=10000)),
                ('level_spring', models.CharField(max_length=10000)),
                ('status', models.CharField(choices=[('NW', 'новая запись'), ('PG', 'модератор взял в работу'), ('AD', 'модерация прошла успешно'), ('RD', 'модерация прошла, информация не принята')], max_length=256)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addbd.coordinates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addbd.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addbd.passes')),
            ],
        ),
    ]
