# Generated by Django 4.2.10 on 2024-02-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addbd', '0002_alter_passes_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='passes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addbd.passes'),
        ),
        migrations.AlterField(
            model_name='passes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addbd.users'),
        ),
    ]
