# Generated by Django 4.2.10 on 2024-02-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addbd', '0004_alter_passes_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addbd.coordinates'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=10000),
        ),
    ]
