# Generated by Django 4.2.10 on 2024-03-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addbd', '0006_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passes',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
    ]
